export const projects = {
    "winstons-portfolio": {
        "site": "https://winstonsportfolio.netlify.app/",
        "git": "https://github.com/loudringphone/portfolio",
        "article": "This is my first portfolio and the one you are looking at now is my second one. As a junior software developer with a background in accountancy, I possess strong reasoning, problem-solving, and skimming skills. I am particularly proud of my skimming skill as software engineers need to read a lot of documentation. This skill also helps me how to identify key words easily and get myself better at Google search. My projects reflect the effort I have dedicated to mastering both front-end and back-end development, enabling me to swiftly set up and deploy applications within a 15-minute timeframe. I have taught myself how to implement the Stripe payment system using Stripe webhooks and Firebase cloud functions. This experience has instilled in me the confidence to tackle challenges fearlessly on any cloud platforms that my future employer may use. I consider myself a creative and curious person. If you like my works and ideas, please do not hesitate to contact me and discuss any career opportunities!"
    },
    "winstons-blog": {
        "site": "https://winstonsblog.netlify.app/",
        "git": "https://github.com/loudringphone/blog-editor",
        "article": "I wanted to express my gratitude to Daniel Lord-Doyle for recognizing my efforts! He presented me with a challenge to create a headless CMS that could be for real business use. This CMS will enable non-technical staff to effortlessly update blog posts on the company website. Using React JS and Firebase, along with the npm package Quill as a text editor, I completed the project in just four days. Interestingly, the CMS I created turned into my personal blog, where I've shared my projects and articles for everyone to read. It was a rewarding experience to work on and I thoroughly enjoyed the process of building and creating something useful. Looking ahead, I am excited to take on the next challenge of learning how to use Strapi and REMIX. You can check out my new blog to explore my projects and articles. Your feedback and support are highly appreciated!"
    },
    "video-store": {
        "site": "https://videostore.netlify.app/",
        "git": "https://github.com/loudringphone/videostore",
        "article": "In my journey as a software engineer following completion of the General Assembly software engineering course, the Video Store project marked a significant milestone. Employing a diverse tech stack including React JS for the frontend, Firebase for the backend, and Stripe for secure payments, I navigated the challenges of integrating Firebase Cloud Functions and Stripe Webhooks for seamless communication. Video Store's frontend was crafted with React JS, enabling an engaging and responsive shopping experience. Leveraging Firebase's capabilities, the backend offered real-time data synchronization, user authentication, and scalable database management, vital for an effective eCommerce platform. To elevate user experience, Redux Persist stored wishlist and cart data locally, ensuring preferences persisted even across sessions. Firebase integration synchronized user data across devices, guaranteeing consistency. Integrating Stripe posed challenges, but available documentation guided me to establish a secure payment platform, enhancing customer confidence during checkout. Through Firebase Cloud Functions and Stripe Webhooks, real-time communication between Firebase and Stripe facilitated prompt updates on payment events. Video Store's creation deepened my grasp of React JS, Firebase, and Stripe integration. The fusion of Redux Persist, Firebase, Stripe, and real-time communication capabilities through Cloud Functions and Webhooks culminated in an efficient, user-friendly eCommerce platform. This project has ignited my software engineering passion, driving me to eagerly embrace future challenges and innovate further."},
        "spark-studio": {
            "site":"https://sparkstudio.netlify.app/",
            "git": "https://github.com/loudringphone/product-development-agency",
            "article": "Spark Studio, an exceptional product development agency website, emerged from a fruitful collaboration between skilled software developers and UX designers during an exciting collab-athon event. By harnessing React.js and Firebase, the team crafted a dynamic, user-friendly platform spotlighting their impressive project portfolio. This article delves into Spark Studio's key attributes, particularly its adept presentation of a diverse project range. The collab-athon experience showcased the potent synergy of teamwork, creativity, and collaboration. Developers and designers harmoniously pooled their talents to construct a cutting-edge product development agency website. The tech stack encompassed React.js for seamless, interactive user experiences. Complementing this, Firebase handled backend and data management, enabling real-time data synchronization and dynamic content updates sans constant page reloads. A prominent feature of Spark Studio is its compelling portfolio display. Showcasing a versatile array of projects, the portfolio offers insights into the team's proficiency and innovative product development approaches, serving both clients and visitors. The UX designers contributed significantly by fashioning an elegant, user-friendly interface. Through a clean layout, intuitive navigation, and impactful visuals, visitors effortlessly explore the portfolio, gaining insight into the team's creative endeavors. Detailed project descriptions enrich comprehension, spotlighting challenges, solutions, and outcomes. This comprehensive insight not only underscores technical prowess but also acts as a valuable resource for prospective clients evaluating Spark Studio's capabilities. Spark Studio's portfolio attests to collaborative spirit, technical acumen, and user-centric ethos. Powered by React.js and Firebase, their website not only showcases projects but also ensures an engaging, informative user experience. Spark Studio remains primed to embrace fresh challenges, continuing its commitment to innovation and excellence in product development."},
            "sancbook": {
                "site": "https://www.youtube.com/embed/7fH1DrjlxoU",
                "git": "https://github.com/loudringphone/sancbook",
                "article": "Sancbook, my second General Assembly project, is a robust social media platform rooted in justice and solidarity. By leveraging Ruby on Rails and PostgreSQL, it unites users globally against human rights abuses. A standout feature is an interactive world map, dynamically powered by the Gon gem, demonstrating its impact. Other key attributes include data scraping from Wikipedia and YouTube, real-time messaging via Ajax, and Rails Active Record Validations for data integrity. Sancbook empowers a global community to address sanctions and human rights issues, connecting like-minded individuals to stand against injustice. Built on Ruby on Rails and PostgreSQL, it offers seamless data management, fostering a user-friendly experience. The platform's interactive world map, driven by the Gon gem, showcases users' global reach, providing a visual representation of collective efforts. Data scraping from Wikipedia and YouTube enhances advocacy through informed content. Real-time collaboration is enabled via instant messaging with Ajax, facilitating discussions and coordination. Rails Active Record Validations ensure data accuracy, guiding users through a smooth signup process. Sancbook exemplifies technology's potential for positive change, uniting users worldwide for justice. Its robust features, powered by Ruby on Rails and PostgreSQL, along with the dynamic interactive map using Gon, empower users to make a significant impact in the fight against human rights abuses, reflecting a dynamic commitment to justice and compassion."},
                "ultimate-tic-tac-toe" : {
                    "site": "https://loudringphone.github.io/ultimate-tictactoe/",
                    "git": "https://loudringphone.github.io/ultimate-tictactoe/",
                    "article": "Ultimate Tic Tac Toe, a standout project from the General Assembly software engineering course, encompasses two captivating games - Ultimate Tic Tac Toe and Tic Tac Toe. This creation features interactive gameplay, self-built AI algorithms, DOM manipulation with vanilla JavaScript, character selection, local storage, board reset, and sound effects, providing an enriching learning experience. The article delves into the immersive world of Ultimate Tic Tac Toe, spotlighting acquired insights and advanced AI techniques employed throughout development. The game offers engaging gameplay through intuitive moves and seamless user interaction, thanks to DOM manipulation. Character selection adds a personalized touch, while local storage preserves progress, and sound effects enhance immersion. A noteworthy achievement is the incorporation of AI opponents. Starting with Minimax AI for Tic Tac Toe, the project evolved to masterful AI strategies, including alpha-beta pruning, board evaluation, and search depth, enriching the gaming experience. Ultimate Tic Tac Toe features a successful integration of the advanced Minimax AI, elevating the challenge with strategic moves. This project signifies the potency of dedication and learning in software development, exemplifying creativity and mastery in game development. As the journey of software engineering advances, this project stands as a foundation for conquering new challenges and further pushing the frontiers of AI and game development."},
}